from abc import ABC, abstractmethod
from typing import Any
from src.capabilities.schema import TargetRef

class SurfaceAdapter(ABC):
    @abstractmethod
    async def start(self, entry_url: str) -> None: ...
    @abstractmethod
    async def close(self) -> None: ...
    @abstractmethod
    async def snapshot(self) -> dict[str, Any]: ...
    @abstractmethod
    async def goto(self, url: str) -> None: ...
    @abstractmethod
    async def click(self, target: TargetRef, timeout_ms: int = 5000) -> None: ...
    @abstractmethod
    async def fill(self, target: TargetRef, value: str, timeout_ms: int = 5000) -> None: ...
    @abstractmethod
    async def extract(self, target: TargetRef, timeout_ms: int = 5000) -> str: ...
    @abstractmethod
    async def visible_text(self, text: str, timeout_ms: int = 2000) -> bool: ...
    @abstractmethod
    async def screenshot(self, path: str) -> None: ...
    @property
    @abstractmethod
    def current_url(self) -> str: ...
